services:
  postgres-chat:
    image: postgres:16.2
    restart: unless-stopped
    container_name: postgres_chat
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data

  inference-01:
    image: microslac/inference-note
    restart: unless-stopped
    container_name: inference_01
    build:
      dockerfile: ./note/Dockerfile
      context: .
    environment:
      MODEL_ID: "meta-llama/Meta-Llama-3-8B-Instruct"
      HUGGING_FACE_HUB_TOKEN: "$HF_TOKEN"
      CUDA_MEMORY_FRACTION: "0.9"
    volumes:
      - $HOME/.cache/huggingface/hub:/data
      - ./notes:/usr/src/notes
    ports:
      - "10017:80"
      - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  inference-02:
    image: microslac/inference-note
    restart: unless-stopped
    container_name: inference_02
    build:
      dockerfile: ./note/Dockerfile
      context: .
    environment:
      HUGGING_FACE_HUB_TOKEN: "$HF_TOKEN"
      MODEL_ID: "microsoft/phi-2"
      CUDA_MEMORY_FRACTION: "0.5"
      QUANTIZE: "bitsandbytes-fp4"
    volumes:
      - $HOME/.cache/huggingface/hub:/data
      - ./notes:/usr/src/notes
    ports:
      - "10019:80"
      - "9999:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    depends_on:
      - inference-01

  chat:
    image: microslac/chat
    restart: unless-stopped
    container_name: chat
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      ENVIRONMENT: "dev"
    env_file:
      - .env
    ports:
      - "8017:8017"
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /app/src
        - action: rebuild
          path: ./requirements
    depends_on:
      - postgres-chat

volumes:
  postgres-data: null
